// <auto-generated />
using System;
using CRM.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251019155628_UpdateProductToAddFloor")]
    partial class UpdateProductToAddFloor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM.Domain.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("account_code");

                    b.Property<string>("AccountDescription")
                        .HasColumnType("text")
                        .HasColumnName("account_description");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_name");

                    b.Property<int?>("AccountTypeId")
                        .HasColumnType("int")
                        .HasColumnName("account_type_id");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("AccountId")
                        .HasName("PK__account__46A222CD5CDE738C");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex(new[] { "AccountName" }, "UQ__account__6894C54A60BF4609")
                        .IsUnique();

                    b.ToTable("account", null, t =>
                        {
                            t.HasTrigger("trg_generate_account_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.AccountType", b =>
                {
                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int")
                        .HasColumnName("account_type_id");

                    b.Property<string>("AccountTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("account_type_code");

                    b.Property<string>("AccountTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("account_type_name");

                    b.HasKey("AccountTypeId")
                        .HasName("PK__account___18186C1005C3471B");

                    b.HasIndex(new[] { "AccountTypeCode" }, "UQ__account___72584A925BFECCC9")
                        .IsUnique();

                    b.ToTable("account_type", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("ContactAddress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contact_address");

                    b.Property<string>("ContactDescription")
                        .HasColumnType("text")
                        .HasColumnName("contact_description");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contact_phone");

                    b.Property<int?>("ContactSalutationId")
                        .HasColumnType("int")
                        .HasColumnName("contact_salutation_id");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ContactId")
                        .HasName("PK__contact__024E7A865A3BC2F9");

                    b.HasIndex("ContactSalutationId");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.ContactSalutation", b =>
                {
                    b.Property<int>("ContactSalutationId")
                        .HasColumnType("int")
                        .HasColumnName("contact_salutation_id");

                    b.Property<string>("ContactSalutationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contact_salutation_code");

                    b.Property<string>("ContactSalutationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contact_salutation_name");

                    b.HasKey("ContactSalutationId")
                        .HasName("PK__contact___9150F11019B4E364");

                    b.HasIndex(new[] { "ContactSalutationCode" }, "UQ__contact___9D12EB252B505BE9")
                        .IsUnique();

                    b.ToTable("contact_salutation", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountAfterTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountBeforeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contract_code");

                    b.Property<string>("ContractDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_description");

                    b.Property<DateOnly>("ContractEndDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_end_date");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contract_name");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractStageId")
                        .HasColumnType("int")
                        .HasColumnName("contract_stage_id");

                    b.Property<DateOnly>("ContractStartDate")
                        .HasColumnType("date")
                        .HasColumnName("contract_start_date");

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int")
                        .HasColumnName("contract_type_id");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DaysRemaining")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("days_remaining")
                        .HasComputedColumnSql("(datediff(day,getdate(),[contract_end_date]))", false);

                    b.Property<int>("DepositId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Seller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ContractId")
                        .HasName("PK__contract__F8D66423B14F7943");

                    b.HasIndex("ContractStageId");

                    b.HasIndex("ContractTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DepositId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductId");

                    b.ToTable("contract", null, t =>
                        {
                            t.HasTrigger("trg_generate_contract_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.ContractItem", b =>
                {
                    b.Property<int>("ContractItemId")
                        .HasColumnType("int")
                        .HasColumnName("contract_item_id");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<decimal?>("CostTax")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("cost_tax");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("grand_total");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("sale_price");

                    b.HasKey("ContractItemId")
                        .HasName("PK__contract__2BA8AB28E5BF6019");

                    b.HasIndex("ContractId");

                    b.HasIndex("ProductId");

                    b.ToTable("contract_item", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.ContractStage", b =>
                {
                    b.Property<int>("ContractStageId")
                        .HasColumnType("int")
                        .HasColumnName("contract_stage_id");

                    b.Property<string>("ContractStageCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contract_stage_code");

                    b.Property<string>("ContractStageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("contract_stage_name");

                    b.HasKey("ContractStageId")
                        .HasName("PK__contract__497F563BB890CF74");

                    b.HasIndex(new[] { "ContractStageCode" }, "UQ__contract__0A4D9136E656C356")
                        .IsUnique();

                    b.ToTable("contract_stage", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.ContractType", b =>
                {
                    b.Property<int>("ContractTypeId")
                        .HasColumnType("int")
                        .HasColumnName("contract_type_id");

                    b.Property<string>("ContractTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contract_type_code");

                    b.Property<string>("ContractTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("contract_type_name");

                    b.HasKey("ContractTypeId")
                        .HasName("PK__contract__B66967DF985EED60");

                    b.HasIndex(new[] { "ContractTypeCode" }, "UQ__contract__E404FEBA8221DE44")
                        .IsUnique();

                    b.ToTable("contract_type", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("customer_address");

                    b.Property<DateOnly?>("CustomerBirthDay")
                        .HasColumnType("date")
                        .HasColumnName("customer_birth_day");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerDescription")
                        .HasColumnType("text")
                        .HasColumnName("customer_description");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("customer_email");

                    b.Property<string>("CustomerIdentityCard")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_identity_card");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("customer_phone");

                    b.Property<int?>("CustomerTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("gender_id");

                    b.HasKey("CustomerId")
                        .HasName("PK__customer__CD65CB85F7CC399B");

                    b.HasIndex("CustomerTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GenderId");

                    b.ToTable("customer", null, t =>
                        {
                            t.HasTrigger("trg_generate_customer_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.CustomerContact", b =>
                {
                    b.Property<int>("CustomerContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_contact_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerContactId"));

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("notes");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("role");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("CustomerContactId")
                        .HasName("PK__customer__C474D9294CE65D75");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_contact", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.CustomerType", b =>
                {
                    b.Property<int>("CustomerTypeId")
                        .HasColumnType("int")
                        .HasColumnName("customer_type_id");

                    b.Property<string>("CustomerTypeCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("customer_type_code");

                    b.Property<string>("CustomerTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("customer_type_name");

                    b.HasKey("CustomerTypeId")
                        .HasName("PK__customer__3320C939AF5F6087");

                    b.HasIndex(new[] { "CustomerTypeCode" }, "UQ__customer__9C993D72E755251E")
                        .IsUnique();

                    b.ToTable("customer_type", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Deposit", b =>
                {
                    b.Property<int>("DepositId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("deposit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepositId"));

                    b.Property<int?>("ContactId")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("DepositCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("deposit_code");

                    b.Property<decimal?>("DepositCost")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("deposit_cost");

                    b.Property<string>("DepositName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCreatedContract")
                        .HasColumnType("bit");

                    b.Property<int?>("OpportunityId")
                        .HasColumnType("int")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("DepositId")
                        .HasName("PK__deposit__4450A62AFD23947B");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("ProductId");

                    b.ToTable("deposit", null, t =>
                        {
                            t.HasTrigger("trg_generate_deposit_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EmployeeAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("employee_address");

                    b.Property<DateOnly?>("EmployeeBirthDay")
                        .HasColumnType("date")
                        .HasColumnName("employee_birth_day");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employee_code");

                    b.Property<string>("EmployeeDescription")
                        .HasColumnType("text")
                        .HasColumnName("employee_description");

                    b.Property<string>("EmployeeEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_email");

                    b.Property<string>("EmployeeIdentityCard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeLevelId")
                        .HasColumnType("int")
                        .HasColumnName("employee_level_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("employee_name");

                    b.Property<string>("EmployeePhone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employee_phone");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("gender_id");

                    b.HasKey("EmployeeId")
                        .HasName("PK__employee__C52E0BA8E5913651");

                    b.HasIndex("EmployeeLevelId");

                    b.HasIndex("GenderId");

                    b.ToTable("employee", null, t =>
                        {
                            t.HasTrigger("trg_generate_employee_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.EmployeeLevel", b =>
                {
                    b.Property<int>("EmployeeLevelId")
                        .HasColumnType("int")
                        .HasColumnName("employee_level_id");

                    b.Property<string>("EmployeeLevelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_level_code");

                    b.Property<string>("EmployeeLevelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("employee_level_name");

                    b.HasKey("EmployeeLevelId")
                        .HasName("PK__employee__5FAC047D0FE5CA9B");

                    b.HasIndex(new[] { "EmployeeLevelCode" }, "UQ__employee__8E85B61F02F868A4")
                        .IsUnique();

                    b.ToTable("employee_level", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .HasColumnType("int")
                        .HasColumnName("gender_id");

                    b.Property<string>("GenderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gender_code");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("gender_name");

                    b.HasKey("GenderId")
                        .HasName("PK__gender__9DF18F8740D2A275");

                    b.HasIndex(new[] { "GenderCode" }, "UQ__gender__DD0984216B1A6BD5")
                        .IsUnique();

                    b.ToTable("gender", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.InstallmentSchedule", b =>
                {
                    b.Property<int>("InstallmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("installment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstallmentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<decimal>("ContractValuePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("InstallmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InstallmentNo")
                        .HasColumnType("int")
                        .HasColumnName("installment_no");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("InstallmentId")
                        .HasName("PK__installm__B591CAB10D8F0C3D");

                    b.HasIndex("ContractId");

                    b.ToTable("installment_schedule", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("InstallmentScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("invoice_code");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.HasKey("InvoiceId")
                        .HasName("PK__invoice__F58DFD497D919D36");

                    b.HasIndex("ContractId");

                    b.HasIndex("InstallmentScheduleId");

                    b.ToTable("invoice", null, t =>
                        {
                            t.HasTrigger("trg_generate_invoice_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.Lead", b =>
                {
                    b.Property<int>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lead_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Daypassed")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("daypassed")
                        .HasComputedColumnSql("(datediff(day,[create_date],getdate()))", false);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeadAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lead_address");

                    b.Property<string>("LeadCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("lead_code");

                    b.Property<string>("LeadDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lead_description");

                    b.Property<string>("LeadEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lead_email");

                    b.Property<string>("LeadName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lead_name");

                    b.Property<string>("LeadPhone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lead_phone");

                    b.Property<int?>("LeadPotentialLevelId")
                        .HasColumnType("int")
                        .HasColumnName("lead_potential_level_id");

                    b.Property<int?>("LeadSourceId")
                        .HasColumnType("int")
                        .HasColumnName("lead_source_id");

                    b.Property<int?>("LeadStageId")
                        .HasColumnType("int")
                        .HasColumnName("lead_stage_id");

                    b.HasKey("LeadId")
                        .HasName("PK__lead__B54D340B1F70EFB1");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeadPotentialLevelId");

                    b.HasIndex("LeadSourceId");

                    b.HasIndex("LeadStageId");

                    b.ToTable("lead", null, t =>
                        {
                            t.HasTrigger("trg_generate_lead_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.LeadItem", b =>
                {
                    b.Property<int>("LeadProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lead_product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadProductId"));

                    b.Property<int?>("LeadId")
                        .HasColumnType("int")
                        .HasColumnName("lead_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.HasKey("LeadProductId")
                        .HasName("PK__lead_ite__8100A3806102DEA9");

                    b.HasIndex("LeadId");

                    b.HasIndex("ProductId");

                    b.ToTable("lead_item", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.LeadPotentialLevel", b =>
                {
                    b.Property<int>("LeadPotentialLevelId")
                        .HasColumnType("int")
                        .HasColumnName("lead_potential_level_id");

                    b.Property<string>("LeadPotentialLevelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lead_potential_level_code");

                    b.Property<string>("LeadPotentialLevelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("lead_potential_level_name");

                    b.HasKey("LeadPotentialLevelId")
                        .HasName("PK__lead_pot__6827B4C11739CE98");

                    b.HasIndex(new[] { "LeadPotentialLevelCode" }, "UQ__lead_pot__53434C60F73BDA88")
                        .IsUnique();

                    b.ToTable("lead_potential_level", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.LeadSource", b =>
                {
                    b.Property<int>("LeadSourceId")
                        .HasColumnType("int")
                        .HasColumnName("lead_source_id");

                    b.Property<string>("LeadSourceCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lead_source_code");

                    b.Property<string>("LeadSourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lead_source_name");

                    b.HasKey("LeadSourceId")
                        .HasName("PK__lead_sou__02D65A87980A8D25");

                    b.HasIndex(new[] { "LeadSourceCode" }, "UQ__lead_sou__A5D86DD3C57A1E19")
                        .IsUnique();

                    b.ToTable("lead_source", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.LeadStage", b =>
                {
                    b.Property<int>("LeadStageId")
                        .HasColumnType("int")
                        .HasColumnName("lead_stage_id");

                    b.Property<string>("LeadStageCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lead_stage_code");

                    b.Property<string>("LeadStageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("lead_stage_name");

                    b.HasKey("LeadStageId")
                        .HasName("PK__lead_sta__A53C6BB77B6BCA7C");

                    b.HasIndex(new[] { "LeadStageCode" }, "UQ__lead_sta__30AC28F616E2B8D1")
                        .IsUnique();

                    b.ToTable("lead_stage", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Opportunity", b =>
                {
                    b.Property<int>("OpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("opportunity_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpportunityId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int?>("DaysRemaining")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("days_remaining")
                        .HasComputedColumnSql("(datediff(day,getdate(),[end_date]))", false);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("OpportunityCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("opportunity_code");

                    b.Property<string>("OpportunityDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opportunity_description");

                    b.Property<string>("OpportunityName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("opportunity_name");

                    b.Property<int>("OpportunityStageId")
                        .HasColumnType("int")
                        .HasColumnName("opportunity_stage_id");

                    b.HasKey("OpportunityId")
                        .HasName("PK__opportun__B975AC8A7F8DAB17");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OpportunityStageId");

                    b.ToTable("opportunity", null, t =>
                        {
                            t.HasTrigger("trg_generate_oop_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.OpportunityItem", b =>
                {
                    b.Property<int>("OpportunityItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("opportunity_item_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpportunityItemId"));

                    b.Property<decimal?>("ExceptedProfit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("excepted_profit");

                    b.Property<int?>("OpportunityId")
                        .HasColumnType("int")
                        .HasColumnName("opportunity_id");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("sale_price");

                    b.HasKey("OpportunityItemId")
                        .HasName("PK__opportun__53B445D8027330C6");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("ProductId");

                    b.ToTable("opportunity_item", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.OpportunityStage", b =>
                {
                    b.Property<int>("OpportunityStageId")
                        .HasColumnType("int")
                        .HasColumnName("opportunity_stage_id");

                    b.Property<string>("OpportunityStageCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("opportunity_stage_code");

                    b.Property<string>("OpportunityStageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("opportunity_stage_name");

                    b.HasKey("OpportunityStageId")
                        .HasName("PK__opportun__E987BFFC7B1F3558");

                    b.HasIndex(new[] { "OpportunityStageCode" }, "UQ__opportun__C49CE1D573DD6A67")
                        .IsUnique();

                    b.ToTable("opportunity_stage", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    b.Property<string>("PaymentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_code");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__payment__ED1FC9EA67F77743");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("payment", null, t =>
                        {
                            t.HasTrigger("trg_payment_insert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("payment_method_code");

                    b.Property<string>("PaymentMethodName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("payment_method_name");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__payment___8A3EA9EBA2B5D72B");

                    b.HasIndex(new[] { "PaymentMethodCode" }, "UQ__payment___6403475B05AB8EEE")
                        .IsUnique();

                    b.ToTable("payment_method", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.PaymentOption", b =>
                {
                    b.Property<int>("PaymentOptionId")
                        .HasColumnType("int")
                        .HasColumnName("payment_option_id");

                    b.Property<string>("PaymentOptionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_option_code");

                    b.Property<string>("PaymentOptionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("payment_option_name");

                    b.HasKey("PaymentOptionId")
                        .HasName("PK__payment___331ED182F5DAB06C");

                    b.HasIndex(new[] { "PaymentOptionCode" }, "UQ__payment___41DA7EA88F03517B")
                        .IsUnique();

                    b.ToTable("payment_option", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ProductAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_address");

                    b.Property<decimal?>("ProductArea")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("product_area");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_code");

                    b.Property<int?>("ProductFloors")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("product_name");

                    b.Property<int?>("ProductNumber")
                        .HasColumnType("int")
                        .HasColumnName("product_number");

                    b.Property<decimal?>("ProductPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("product_price");

                    b.Property<int>("ProductStatusId")
                        .HasColumnType("int")
                        .HasColumnName("product_status_id");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.HasKey("ProductId")
                        .HasName("PK__product__47027DF5BB0B796C");

                    b.HasIndex("ProductStatusId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("product", null, t =>
                        {
                            t.HasTrigger("trg_generate_product_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.ProductStatus", b =>
                {
                    b.Property<int>("ProductStatusId")
                        .HasColumnType("int")
                        .HasColumnName("product_status_id");

                    b.Property<string>("ProductStatusCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_status_code");

                    b.Property<string>("ProductStatusName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("product_status_name");

                    b.HasKey("ProductStatusId")
                        .HasName("PK__product___D299CFCF5E40536F");

                    b.ToTable("product_status", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.ProductType", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int")
                        .HasColumnName("product_type_id");

                    b.Property<string>("ProductTypeCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("product_type_code");

                    b.Property<string>("ProductTypeName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("nvarchar")
                        .HasColumnName("product_type_name");

                    b.HasKey("ProductTypeId")
                        .HasName("PK__product___6EED3ED647063BD9");

                    b.ToTable("product_type", (string)null);
                });

            modelBuilder.Entity("CRM.Domain.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DaysRemaining")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("days_remaining")
                        .HasComputedColumnSql("(case when [project_end_date]>=CONVERT([date],getdate()) then datediff(day,CONVERT([date],getdate()),[project_end_date]) else (0) end)", false);

                    b.Property<string>("ProjectAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("project_address");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("project_code");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("project_description");

                    b.Property<DateOnly?>("ProjectEndDate")
                        .HasColumnType("date")
                        .HasColumnName("project_end_date");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("project_name");

                    b.Property<DateOnly?>("ProjectStartDate")
                        .HasColumnType("date")
                        .HasColumnName("project_start_date");

                    b.Property<string>("ProjectStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("project_status");

                    b.Property<decimal?>("TotalArea")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProjectId")
                        .HasName("PK__project__BC799E1FA2A8F03D");

                    b.ToTable("project", null, t =>
                        {
                            t.HasTrigger("trg_generate_project_code");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("CRM.Domain.Models.Account", b =>
                {
                    b.HasOne("CRM.Domain.Models.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .HasConstraintName("fk_account_type");

                    b.HasOne("CRM.Domain.Models.Employee", "Employee")
                        .WithMany("Accounts")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_account_employee");

                    b.Navigation("AccountType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CRM.Domain.Models.Contact", b =>
                {
                    b.HasOne("CRM.Domain.Models.ContactSalutation", "ContactSalutation")
                        .WithMany("Contacts")
                        .HasForeignKey("ContactSalutationId")
                        .HasConstraintName("fk_contact_salutation");

                    b.Navigation("ContactSalutation");
                });

            modelBuilder.Entity("CRM.Domain.Models.Contract", b =>
                {
                    b.HasOne("CRM.Domain.Models.ContractStage", "ContractStage")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractStageId")
                        .IsRequired()
                        .HasConstraintName("fk_contract_stage");

                    b.HasOne("CRM.Domain.Models.ContractType", "ContractType")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_contract_type");

                    b.HasOne("CRM.Domain.Models.Customer", "Customer")
                        .WithMany("Contracts")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_contract_customer");

                    b.HasOne("CRM.Domain.Models.Deposit", "Deposit")
                        .WithMany()
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Models.Employee", "Employee")
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("fk_contract_employee");

                    b.HasOne("CRM.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractStage");

                    b.Navigation("ContractType");

                    b.Navigation("Customer");

                    b.Navigation("Deposit");

                    b.Navigation("Employee");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CRM.Domain.Models.ContractItem", b =>
                {
                    b.HasOne("CRM.Domain.Models.Contract", "Contract")
                        .WithMany("ContractItems")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_citem_contract");

                    b.HasOne("CRM.Domain.Models.Product", "Product")
                        .WithMany("ContractItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_citem_product");

                    b.Navigation("Contract");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CRM.Domain.Models.Customer", b =>
                {
                    b.HasOne("CRM.Domain.Models.CustomerType", "CustomerType")
                        .WithMany()
                        .HasForeignKey("CustomerTypeId");

                    b.HasOne("CRM.Domain.Models.Employee", "Employee")
                        .WithMany("Customers")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_customer_employee");

                    b.HasOne("CRM.Domain.Models.Gender", "Gender")
                        .WithMany("Customers")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("fk_customer_gender");

                    b.Navigation("CustomerType");

                    b.Navigation("Employee");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("CRM.Domain.Models.CustomerContact", b =>
                {
                    b.HasOne("CRM.Domain.Models.Contact", "Contact")
                        .WithMany("CustomerContacts")
                        .HasForeignKey("ContactId")
                        .IsRequired()
                        .HasConstraintName("fk_customer_contact_contact");

                    b.HasOne("CRM.Domain.Models.Customer", "Customer")
                        .WithMany("CustomerContacts")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_customer_contact_customer");

                    b.Navigation("Contact");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM.Domain.Models.Deposit", b =>
                {
                    b.HasOne("CRM.Domain.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");

                    b.HasOne("CRM.Domain.Models.Customer", "Customer")
                        .WithMany("Deposits")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_deposit_customer");

                    b.HasOne("CRM.Domain.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("CRM.Domain.Models.Opportunity", "Opportunity")
                        .WithMany("Deposits")
                        .HasForeignKey("OpportunityId")
                        .HasConstraintName("fk_deposit_opportunity");

                    b.HasOne("CRM.Domain.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Opportunity");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CRM.Domain.Models.Employee", b =>
                {
                    b.HasOne("CRM.Domain.Models.EmployeeLevel", "EmployeeLevel")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeLevelId")
                        .HasConstraintName("fk_employee_level");

                    b.HasOne("CRM.Domain.Models.Gender", "Gender")
                        .WithMany("Employees")
                        .HasForeignKey("GenderId")
                        .HasConstraintName("fk_employee_gender");

                    b.Navigation("EmployeeLevel");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("CRM.Domain.Models.InstallmentSchedule", b =>
                {
                    b.HasOne("CRM.Domain.Models.Contract", "Contract")
                        .WithMany("InstallmentSchedules")
                        .HasForeignKey("ContractId")
                        .IsRequired()
                        .HasConstraintName("fk_installment_contract");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("CRM.Domain.Models.Invoice", b =>
                {
                    b.HasOne("CRM.Domain.Models.Contract", "Contract")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractId")
                        .IsRequired()
                        .HasConstraintName("fk_invoice_contract");

                    b.HasOne("CRM.Domain.Models.InstallmentSchedule", "InstallmentSchedule")
                        .WithMany()
                        .HasForeignKey("InstallmentScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("InstallmentSchedule");
                });

            modelBuilder.Entity("CRM.Domain.Models.Lead", b =>
                {
                    b.HasOne("CRM.Domain.Models.Employee", "Employee")
                        .WithMany("Leads")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("fk_lead_employee");

                    b.HasOne("CRM.Domain.Models.LeadPotentialLevel", "LeadPotentialLevel")
                        .WithMany("Leads")
                        .HasForeignKey("LeadPotentialLevelId")
                        .HasConstraintName("fk_lead_potential");

                    b.HasOne("CRM.Domain.Models.LeadSource", "LeadSource")
                        .WithMany("Leads")
                        .HasForeignKey("LeadSourceId")
                        .HasConstraintName("fk_lead_source");

                    b.HasOne("CRM.Domain.Models.LeadStage", "LeadStage")
                        .WithMany("Leads")
                        .HasForeignKey("LeadStageId")
                        .HasConstraintName("fk_lead_stage");

                    b.Navigation("Employee");

                    b.Navigation("LeadPotentialLevel");

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStage");
                });

            modelBuilder.Entity("CRM.Domain.Models.LeadItem", b =>
                {
                    b.HasOne("CRM.Domain.Models.Lead", "Lead")
                        .WithMany("LeadItems")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_leaditem_lead");

                    b.HasOne("CRM.Domain.Models.Product", "Product")
                        .WithMany("LeadItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_leaditem_product");

                    b.Navigation("Lead");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CRM.Domain.Models.Opportunity", b =>
                {
                    b.HasOne("CRM.Domain.Models.Customer", "Customer")
                        .WithMany("Opportunities")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_opp_customer");

                    b.HasOne("CRM.Domain.Models.Employee", "Employee")
                        .WithMany("Opportunities")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("fk_opp_employee");

                    b.HasOne("CRM.Domain.Models.OpportunityStage", "OpportunityStage")
                        .WithMany("Opportunities")
                        .HasForeignKey("OpportunityStageId")
                        .IsRequired()
                        .HasConstraintName("fk_opp_stage");

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("OpportunityStage");
                });

            modelBuilder.Entity("CRM.Domain.Models.OpportunityItem", b =>
                {
                    b.HasOne("CRM.Domain.Models.Opportunity", "Opportunity")
                        .WithMany("OpportunityItems")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_oppitem_op");

                    b.HasOne("CRM.Domain.Models.Product", "Product")
                        .WithMany("OpportunityItems")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_oppitem_product");

                    b.Navigation("Opportunity");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CRM.Domain.Models.Payment", b =>
                {
                    b.HasOne("CRM.Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM.Domain.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("fk_payment_invoice");

                    b.HasOne("CRM.Domain.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("fk_payment_method");

                    b.Navigation("Customer");

                    b.Navigation("Invoice");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("CRM.Domain.Models.Product", b =>
                {
                    b.HasOne("CRM.Domain.Models.ProductStatus", "ProductStatus")
                        .WithMany("Products")
                        .HasForeignKey("ProductStatusId")
                        .IsRequired()
                        .HasConstraintName("fk_product_status");

                    b.HasOne("CRM.Domain.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_product_type");

                    b.HasOne("CRM.Domain.Models.Project", "Project")
                        .WithMany("Products")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_product_project");

                    b.Navigation("ProductStatus");

                    b.Navigation("ProductType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CRM.Domain.Models.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("CRM.Domain.Models.Contact", b =>
                {
                    b.Navigation("CustomerContacts");
                });

            modelBuilder.Entity("CRM.Domain.Models.ContactSalutation", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("CRM.Domain.Models.Contract", b =>
                {
                    b.Navigation("ContractItems");

                    b.Navigation("InstallmentSchedules");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("CRM.Domain.Models.ContractStage", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("CRM.Domain.Models.ContractType", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("CRM.Domain.Models.Customer", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("CustomerContacts");

                    b.Navigation("Deposits");

                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("CRM.Domain.Models.Employee", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Contracts");

                    b.Navigation("Customers");

                    b.Navigation("Leads");

                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("CRM.Domain.Models.EmployeeLevel", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CRM.Domain.Models.Gender", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CRM.Domain.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CRM.Domain.Models.Lead", b =>
                {
                    b.Navigation("LeadItems");
                });

            modelBuilder.Entity("CRM.Domain.Models.LeadPotentialLevel", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("CRM.Domain.Models.LeadSource", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("CRM.Domain.Models.LeadStage", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("CRM.Domain.Models.Opportunity", b =>
                {
                    b.Navigation("Deposits");

                    b.Navigation("OpportunityItems");
                });

            modelBuilder.Entity("CRM.Domain.Models.OpportunityStage", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("CRM.Domain.Models.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CRM.Domain.Models.Product", b =>
                {
                    b.Navigation("ContractItems");

                    b.Navigation("LeadItems");

                    b.Navigation("OpportunityItems");
                });

            modelBuilder.Entity("CRM.Domain.Models.ProductStatus", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CRM.Domain.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CRM.Domain.Models.Project", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
